### ISSUE TITLE
Help > Get gravatar image for sidebar

### ISSUE THREAD

**Issue by ghost** [svavs/codinfox-zola#1]
## Before you start

<a href="https://gravatar.com">Get a gravatar account</a> and set this up with a profile image.

## Add gravatar profile image to codinfox-zola theme

1. login to gravatar.com
2. click My Profile
3. click **view profile** in RH sidebar beneath profile name
4. click JSON
5. copy the `hash` value on line 4
6. paste the `hash` value to `author.toml` line 10

**Comment by svavs** [comment]
Thank you for your contribution, it's really appreciated! The Readme is now updated (62e473d).
